"""create conversation messages table

Revision ID: e41acd4b790c
Revises: af34ce304a66
Create Date: 2026-06-02 20:24:47.059084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41acd4b790c'
down_revision: Union[str, None] = 'af34ce304a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('bot_answer', sa.Text(), nullable=False),
    sa.Column('should_collect_lead', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_company_id'), 'conversation_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_visitor_id'), 'conversation_messages', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_visitor_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_company_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
